# Change these first
owner: venkatoriga # Your GitHub organization or username, where this repository lives
repo: origamonitor # The name of this repository

sites:
  - name: Origa Shop
    url: https://www.shop.origa.market
assignees:
