# Change these first
owner: venkatoriga # Your GitHub organization or username, where this repository lives
repo: origamonitor # The name of this repository

sites:
  - name: Origa Shop
    url: https://shop.origa.market
  - name: Origa Staging
    url: https://staging.origa.market
  - name: Origa Test Store
    url: https://teststore.origa.market
  - name: Origa Test Admin
    url: https://testadmin.origa.market
  - name: Origa 
    url: https://origa.market
assignees:
